### ISSUE TITLE
Walking back L1Block by hash

### ISSUE THREAD

**Issue by xueyuchen** [base-org/node#104]
After I restarted the node, the log kept displaying“Walking back L1Block by hash”
How can i fix this problem?

```sh
node-node-1  | 2023-09-04T07:11:59.146150217Z t=2023-09-04T07:11:59+0000 lvl=info msg="Walking back L1Block by hash"      curr=0x63f3fef36c1ee69e8bb870816291d08be18e1ae10bab4b5b03f6c35dd2039d80:18038938 next=0x9515e052caee68634b8b30715ea737c24609bd8bbc5ebb47a36c819a9ccdf5f6:18038937 l2block=0xa36503bcce2948b5d95ad6c84c146d3c566060950a2ec0b6b0a2570dc5f28072:3374342
node-node-1  | 2023-09-04T07:11:59.146150217Z t=2023-09-04T07:11:59+0000 lvl=info msg="Walking back L1Block by hash"      curr=0x63f3fef36c1ee69e8bb870816291d08be18e1ae10bab4b5b03f6c35dd2039d80:18038938 next=0x9515e052caee68634b8b30715ea737c24609bd8bbc5ebb47a36c819a9ccdf5f6:18038937 l2block=0xa36503bcce2948b5d95ad6c84c146d3c566060950a2ec0b6b0a2570dc5f28072:3374342
node-node-1  | 2023-09-04T07:11:59.448545116Z t=2023-09-04T07:11:59+0000 lvl=info msg="Walking back L1Block by hash"      curr=0x9515e052caee68634b8b30715ea737c24609bd8bbc5ebb47a36c819a9ccdf5f6:18038937 next=0x8c8360a74f0a1bda2ce0816d6baaa4dc53b94bd901ff0cd379e2876c913fe3be:18038936 l2block=0xd13b3a8e05a61b66b8ae6bdf79c02b8847651b1db221e2369b1718ba7ac2afa8:3374336
node-node-1  | 2023-09-04T07:11:59.448545116Z t=2023-09-04T07:11:59+0000 lvl=info msg="Walking back L1Block by hash"      curr=0x9515e052caee68634b8b30715ea737c24609bd8bbc5ebb47a36c819a9ccdf5f6:18038937 next=0x8c8360a74f0a1bda2ce0816d6baaa4dc53b94bd901ff0cd379e2876c913fe3be:18038936 l2block=0xd13b3a8e05a61b66b8ae6bdf79c02b8847651b1db221e2369b1718ba7ac2afa8:3374336
```

**Comment by wbnns** [comment]
@xueyuchen 

This "Walking back L1Block" message indicates that your node is syncing back to a previous Ethereum L1 block. 

Some common reasons why this can happen:

- The node fell behind or crashed and needs to replay blocks to catch up with the latest L1 state. This is normal on restart or if the node was offline for a while.

- There was a chain reorganization on L1 that the L2 node needs to walk back to handle.

- The L1 block data is missing or corrupt and needs to be re-retrieved.

To resolve this:

- Check system resources - CPU, memory, disk space. If overloaded, optimize resources or migrate to a bigger machine.

- If it gets stuck walking back the same blocks, your L1 data may be corrupt. Wipe the data folder and resync from scratch.

- Monitor system logs for any other errors that could be causing problems.

The walking back messages themselves are expected on restart but shouldn't persist too long once caught up. If the node remains stable otherwise, you can likely ignore them during initial sync. But if problems persist, try the steps above to troubleshoot further. 👍

**Comment by MrFrogoz** [comment]
@xueyuchen hi, I also had the same problem, and that log never ended. To resolve this I reset the node and restored with backup "wget https://base-mainnet-archive-snapshots.s3.us-east-1.amazonaws.com/$(curl https://base-mainnet-archive-snapshots .s3.us-east-1.amazonaws.com/latest)", subsequently as L1URL I added my eth cluster and everything started working again, because it seems that with public rpcs, just after sync, I tried to restarted it and I had the same problem
