### ISSUE TITLE
err="etherbase must be explicitly specified"

### ISSUE THREAD

**Issue by ifsayyes** [base-org/node#240]
My base node, using snapshot settings, has also managed to read snapshot blocks. 
I use command "docker compose up --build -d" over 6 hours ago, and it still hasn't started syncing! 

I'm getting the following error: 
"Served eth_coinbase conn=194.67.206.46:33410 reqid=2 duration="76.346µs" err="etherbase must be explicitly specified"

Any experienced folks out there who understand this, please help me out with an answer or a solution.

![image](https://github.com/base-org/node/assets/135924607/99f0cde5-12dc-435c-84ab-e023520ab9e1)

![image](https://github.com/base-org/node/assets/135924607/64bd3053-1acb-45cf-bcd5-35fef1ac9ec8)

![image](https://github.com/base-org/node/assets/135924607/6268a987-afa7-4cca-a734-5b0f3d95d8e4)

![image](https://github.com/base-org/node/assets/135924607/7dba3368-6bcb-41ac-ae20-3514d1b88fc6)

**Comment by ifsayyes** [comment]
My other base node, without using snapshots, 
is syncing blocks directly, which is very slow, 
the synchronization is in progress.

Any experienced folks out there who know how to fix this using snapshot nodes...Tks!
<img width="1337" alt="658a46633e19dfdcb87fb8fb2f1be92" src="https://github.com/base-org/node/assets/135924607/5a78304f-ff50-4c08-8b42-588bcbb8211b">

**Comment by Boyalskyy** [comment]
i have the same issue after restart docker-compose

**Comment by wbnns** [comment]
@ifsayyes Hi there! It looks like the issue here is that `OP_GETH_SYNCMODE` is set to `snap` and the rest of the snap-sync related parameters are commented out. I would recommend you are on the latest version (the head of this repo) and also using the current `.env.mainnet` [link](https://github.com/base-org/node/blob/main/.env.mainnet).

Note, if your node is for production purposes snap-sync mode most likely won't be stable enough as the feature is new and experimental.

If you're still experiencing an issue after making the above changes, please join the [Base Discord](https://base.org/discord) and open a ticket in the `#developer-support` channel.

We can take a closer look their to see what the issue might be.

@ifsayyes Because the snap sync feature is new and experimental, there are not enough peers at present which is most likely what is leading to the latency on your sync.

Hope that helps clarify, you all! Please definitely drop by Base Discord and LMK (wbnns) if you all are still having a problem. We can help you there.
