### ISSUE TITLE
Full Node Windows Support

### ISSUE THREAD

**Issue by 0x9090** [base-org/node#267]
I'm building an application that runs locally on Windows (& Mac & Linux) PCs and uses Base to communicate with other applications. I would like a "1-click" option to start a Base full node on these OS's, but Base seems to require Docker to run. This dependency makes it extremely difficult to programmatically deploy Base full nodes, because Docker Desktop on Windows requires the user to navigate through different splash screens, login, and the Docker service won't automatically start on boot. I have tried configuring Docker Desktop.exe in about every way their documentation specified, and it is still non-user friendly. There's always some UI pop-up or mandatory Docker login that can't be automated before the Docker service starts (especially on Windows)

I would like to request a native way for Base to install a full node on Windows and OSX (silently), without requiring the need for Docker. I can drop a Geth.exe binary and configure it locally, but I need some way to remove Docker from the equation.

Ideally, there would be some pre-compiled .EXE and .DMG that when run, would install ETH geth, Base geth, and start downloading the blockchain on startup, while exposing the RPC API on localhost. That binary should be able to take in a directory path to where the blockchain data is downloaded to - so users could configure the blockchain(s) to download to an external hard drive or network share.

**Comment by wbnns** [comment]
Hi there! A contributor recently published these guides on how to run a Base node without using Docker -- for Windows, I believe you'll need to use the Windows Subsystem for Linux. https://medium.com/@hiroyukinaito.eth/running-base-node-without-docker-part-1-323958adfeeb
https://medium.com/@hiroyukinaito.eth/running-base-node-without-docker-part-2-1c34dbca8909

It's pretty technical but it is possible. With regard to running a DMG/EXE, since there is no user interface and Base Nodes are command line applications, I think it if ultimately this is the goal (quick/easy setup) I would recommend a node provider: https://docs.base.org/tools/node-providers

Hope that helps! :)
