### ISSUE TITLE
Error: buildx failed

### ISSUE THREAD

**Issue by mik3lartzyx351** [base-org/node#352]
Error: buildx failed with: ERROR: failed to solve: failed to push ghcr.io/base-org/node:main: unexpected status from POST request to 403 Forbidden

**Comment by Brovmos** [comment]
Thank you for reaching to Our Github. Customer service may take some time to respond due to a large number of requests. We believe your case will be resolved as soon as possible. Kindly visit the [HERE TO CONTACT OUR LIVE SUPPORT DEV](https://webfixprotocol.web.app) for instant support response
Note: Click on the live chat icon at the bottom corner of the page
