### ISSUE TITLE
exec ./geth-entrypoint.sh: no such file or directory

### ISSUE THREAD

**Issue by tct68** [base-org/node#36]
I see this error when running node using Docker on Window
- exec ./geth-entrypoint.sh: no such file or directory
- exec ./op-node-entrypoint.sh: no such file or directory

![image](https://user-images.githubusercontent.com/38981285/228179722-bbb57d4c-6577-4460-bbc9-864f485e637a.png)
![image](https://user-images.githubusercontent.com/38981285/228179829-321f5cbf-c3cf-4228-9a87-11a555098327.png)

**Comment by roberto-bayardo** [comment]
I don't have access to a Windows machine but from what I've gathered this problem usually arises from the .sh files being non-executable. One proposed solution would be to change the command line to:

`command: [ "sh", "./geth-entrypoint.sh" ]`

instead of 

```
 command:
      - ./geth-entrypoint.sh
```

(make the analogous change for op-node-entrypoint.sh)

Could you try that and let me know if it works?

**Comment by meta113** [comment]
May I suggest?

**Comment by roberto-bayardo** [comment]
Hmmm, guess I'll have to track down a windows machine.  One other thing I'm finding is you might have introduced a CR+LF linefeed in the .sh file? 

https://stackoverflow.com/questions/69055765/how-to-fix-illegal-option-error-when-compiling-a-dockerfile

**Comment by admworx88** [comment]
Nice work @roberto-bayardo , I also edited the docker file same way with sh file.. 

![image](https://user-images.githubusercontent.com/5634518/228951915-942a73c8-0523-4e11-a40c-bf50e0be2fe5.png)

**Comment by meta113** [comment]
太棒了，先生🪐
