### ISSUE TITLE
current sync not kept 

### ISSUE THREAD

**Issue by iht76** [base-org/node#92]
while initial sync, I tried changing the ETH mainnet node.
I had to restart the base node, so I tried with CTL+C , both processes closed, changed the ETH node in .env.mainnet and restarted the node ... it started syncing from 0 !! Didn't keep the previously synced data.

On another occasion I killed the docker containers instead, changed the ETH node and restarted .... same thing, Didnt keep the already synced data and started from 0 !

**Comment by wbnns** [comment]
@iht76 

Heya, this sounds like two separate issues.

> while initial sync, I tried changing the ETH mainnet node.
I had to restart the base node, so I tried with CTL+C , both processes closed, changed the ETH node in .env.mainnet and restarted the node ... it started syncing from 0 !! Didn't keep the previously synced data.

This sounds like it is because the initial sync didn't complete that the chain state got corrupted when the config was updated. I would recommend waiting for the initial sync to complete before doing this.

> On another occasion I killed the docker containers instead, changed the ETH node and restarted .... same thing, Didnt keep the already synced data and started from 0 !

For this, make sure you are running the following commands to stop the container and restart before/after making the changes:
```
docker-compose stop
docker-compose build
docker-compose up
```
If you delete the container or run something like `docker compose down` it will delete everything and you'll need to start over again.
